### ISSUE TITLE
Re: prediction inputs

### ISSUE THREAD

**Issue by xenmind** [config-i1/greybox#20]
Hi,
I really love this package, very accurate and easy to use. This is not a bug, it's more an undesirable change in behaviour between version 0.22 an the current package. I used to be able to feed a single row of features into the forecast/predict function and get a prediction. Now, the prediction function seems to require more than 1 row of data. If I put in a single row, I get this error: 'Error in matrixOfxreg %*% ourVcov %*% t(matrixOfxreg) : non-conformable arguments' So, when rolling a model forward incrementally, I have to use a test set of 2 rows, and then take the last prediction only. Everything still works, but it's slightly inconvenient, and it may be confusing to new users. 

Thanks, Gavin.

**Comment by config-i1** [comment]
Hi Gavin,

Thanks for the feedback! I would still call this a bug. Let me fix this.

Cheers,
Ivan

**Comment by config-i1** [comment]
This should be fixed now in 8882790c6b28f856828c2132b7f77036a28c071d Install package from github if you need this ASAP. Or wait for CRAN release for ~1 month ;)
Let me know if I can fix anything else.
