### ISSUE TITLE
mcor:  x works only if numeric?

### ISSUE THREAD

**Issue by ZellW** [config-i1/greybox#25]
The `mcor` documentation example works:  `mcor(mtcars$am, mtcars$mpg)`.  However, when  `mcor x` is a factor like the example you provide [here](https://forecasting.svetunkov.ru/en/2019/01/07/marketing-analytics-with-greybox/), `mcor(mtcarsData$am, mtcarsData$mpg)` fails with this error:  

> Error in terms.formula(object, data = data) : '.' in formula and no 'data' argument

**Comment by config-i1** [comment]
Thanks for the report. Have you tried the version on github? I think that I've found this bug and managed to fix it in greybox v0.4.1.41003, the version on github. I will upload this version on CRAN next week.
