### ISSUE TITLE
Rename spread function

### ISSUE THREAD

**Issue by config-i1** [config-i1/greybox#37]
There is a conflict with a spread() from tidyr. The options for new names:
- spreadplot()
- explore()
- scatter()
- ...

**Comment by s-spavound** [comment]
I think scatter() is too specific for this function (as it produces more than scatter plots). explore() is perhaps too general. spreadplot() seems like a good option.

**Comment by config-i1** [comment]
Agreed. Let's rename to spreadplot then.

**Comment by config-i1** [comment]
Doesn't look like this will be done anymore :)
