### ISSUE TITLE
Introduce heteroscedasticity model

### ISSUE THREAD

**Issue by config-i1** [config-i1/greybox#46]
This can be a new parameter in alm(), determining the formula for the scale, e.g. sigma^2_j = a_0 + a_1 x_j + a_2 x_j^2:

> scaleFormula = ~x+x^2

 This is relatively easy to implement and it can be estimated together with the parameters for the location (that are already in place) via the maximisation of likelihood. This probably does not make sense for the other losses.

**Comment by Steviey** [comment]
+1

**Comment by config-i1** [comment]
Things to do in alm:

1. scale parameter, accepting formula;
2. model.matrix for scale;
3. Estimation of scale, after getting the location correctly;
4. Return scale formula if it was provided in scale. Otherwise return scale;
5. Accept initial parameters for scale;
6. Modify all methods that use scale;

While step 3 can be done simultaneously, this would complicate and slow down the estimation process. Check how this is done in GAMLSS.

**Comment by config-i1** [comment]
Ths stuff currently works for Normal distribution and might work for others (needs checking).

Things left to do:

- Substitute constant sigma() with the time varying stdev for all in-sample functions (hatvalues, rstandard, rstudent);
- Get variances from time varying scale in predict and other methods (use connection between scale and variance in distributions).
- Make sure that the thing works with all distributions
- Develop scaleModel + occurrence

**Comment by config-i1** [comment]
(1) is done.

**Comment by config-i1** [comment]
A new model and a new approach is being developed in ac1c75999f660c6830d7a1389f3acba0f3e3ad23

**Comment by config-i1** [comment]
sm method for the scale model based on any other linear model.

Things left:
1. Get variances from time varying scale in different methods (use connection between scale and variance in distributions) - need to check if this is needed anywhere else.
2. Make sure that the thing works with all distributions
3. Develop scaleModel + occurrence
4. Make coefbootstrap() work with scaleModel

**Comment by config-i1** [comment]
(4) is done.

**Comment by config-i1** [comment]
Looks like only (3) is left

**Comment by config-i1** [comment]
All done. Now I need to update the vignette.

**Comment by config-i1** [comment]
Done.
