### ISSUE TITLE
ro() + forecast + model type FFF

### ISSUE THREAD

**Issue by Steviey** [config-i1/greybox#50]
Would it make sense, to be able to retrieve the actual final model as characters from a final fit, when using type FFF via forecast and ro()?

**Comment by config-i1** [comment]
You can do that. When you use forecast, the model is saved in object$model$model. Just have a look at the structure of the final object.

**Comment by Steviey** [comment]
When I say ourVal='mean', I don't get any node named 'model'. Where is the trick?

**Comment by config-i1** [comment]
ourValues=c("mean", "lower", "upper", "model$model") - something like this.
