### ISSUE TITLE
alm.R Line 1137

### ISSUE THREAD

**Issue by Steviey** [config-i1/greybox#51]
_R 4.2, greybox 0.6.7.41009_

Hello,

While using ro(), I could locate the root of the error below, to alm.R Line 1137

`simpleError in if (any(corHigh)) {    removexreg <- unique(which(corHigh, arr.ind = TRUE)[, 1])    matrixXreg <- matrixXreg[, -removexreg, drop = FALSE]    nVariables <- ncol(matrixXreg)    variablesNames <- colnames(matrixXreg)    if (!occurrenceModel && !CDF) {        warning("Some exogenous variables were perfectly correlated. We've dropped them out.",             call. = FALSE)    }}: missing value where TRUE/FALSE needed>`

`'value where TRUE/FALSE needed'` suggests that there will be an empty variable proofed- under certain circumstances. However, since this is highly correlated to individual input data- we could fail to reproduce this error with random data.

For now, I avoid this to be a 'tragic code break' by using a tryCatch(), while searching for the right model.

**Comment by config-i1** [comment]
Thanks for this!
Unfortunately, it's difficult to understand why this happens without even knowing how `alm()` was called. If NAs appear in correlation matrix, then there are some missing observations in the data. I can make this a bit more robust by including `use="complete.obs"` in `cor()`, but this won't guarantee the fix of the issue.

**Comment by config-i1** [comment]
Implemented in greybox v0.6.7.41010. Can you, please, install from github and see whether the issues was fix or not?

**Comment by Steviey** [comment]
OK Ivan I will test this. For now, I can mention that all my data is na-imputed by 0.

**Comment by config-i1** [comment]
This is a useful information. Do you use occurrence in this case?

**Comment by Steviey** [comment]
Here is an example paramter-setting. Keep in mind, there are custom/personal setting  listed too.

```
 model      regressors              ic    distribution         initial 
          "FFF"        "select"           "AIC"       "default"   "backcasting" 
           lags          bounds      occurrence         scaleIt        trBoxCox 
            "5"         "usual"          "none"         "FALSE"          "TRUE" 
    orderMethod        pdqSetup      usePdqLags       myOrigins    myDynamicPdq 
         "none"             "2"          "TRUE"             "8"          "TRUE" 
              p               d               q               P               D 
            "0"             "0"             "5"             "0"             "0" 
              Q   boxCoxPdqTest   algoPrintName       algoNName      myGridName 
            "0"             "0" "gaussprRadial"            "n1"      "superMin" 
```

**Comment by config-i1** [comment]
Okay. This looks mysterious. Not sure how to track the error. Let's see if the updated version helps...

**Comment by Steviey** [comment]
By the way, the parameters can be reduced to:

```
model      regressors         ic    distribution         initial 
"FFF"        "select"           "AIC"       "default"   "backcasting" 
lags          bounds      occurrence          
"5"         "usual"          "none"          

```

**Comment by Steviey** [comment]
Update: This did not the trick. What I can say is the following. 
from grid search:
In iteration A it has model='MAN' ic='AICc' result: no error
In iteration B it has model='FFF' ic='AIC' result: the mentioned error.

**Comment by Steviey** [comment]
Let me know, if there is something new to test.

**Comment by config-i1** [comment]
Hi, I got distracted by my job... :) Can you paste a reproducible example, so that I could investigate and fix?

**Comment by Steviey** [comment]
At the moment I can't reproduce it anymore Ivan. There are so many changes in your and in my code. Maybe I was wrong on any code part. I let you know, if this happens again.

**Comment by config-i1** [comment]
I've been fixing so many bugs recently, that I could have fixed it by accident :)
Thanks!

**Comment by config-i1** [comment]
I've been fixing so many bugs recently, that I could have fixed it by accident :)
Thanks!
