### ISSUE TITLE
Warning '.recacheSubclasses'

### ISSUE THREAD

**Issue by Steviey** [config-i1/greybox#56]
I switched to greybox dev-version to participate from the alm-fix.
I guess, since then I see the following warning more often:

```
	Warning messages:
1: In .recacheSubclasses(def@className, def, env) :
  undefined subclass "numericVector" of class "Mnumeric"; definition not updated
```
Could it be greybox-related, or is it related to smooth?

**Comment by config-i1** [comment]
Hi,
Thanks for that report! When do you get this warning? Can you please provide reproducible example?

**Comment by config-i1** [comment]
Actually, Google tells me that "Mnumeric" is the class exported by "Matrix" package and that people had similar issues (e.g. here: https://discourse.mc-stan.org/t/weird-message-recachesubclasses-mnumeric/22362/5 )

**Comment by Steviey** [comment]
_Ubuntu 16.4_
Thanks for the lead Ivan. Seems to be an external problem. I have to check it. Currently I'm blocked by a heavy duty job.

**Comment by Steviey** [comment]
This seems to be duplicated with https://github.com/config-i1/greybox/issues/54

**Comment by config-i1** [comment]
Okay. Cheers!
