### ISSUE TITLE
forecast function is conflicting with "forecast" package

### ISSUE THREAD

**Issue by alsabtay** [config-i1/greybox#60]
I get an error when I use forecast() function when I use "forecast" and "smooth" packages at the same time. The forecast() function with auto.arima() model returns two outputs: "pred" and "se".

The problem arises due to call "smooth" package before "forecast" package. I think that the problem arises due to conflict with "greybox::forecast" and "forecast::forecast()" function.

**Comment by config-i1** [comment]
This is now fixed in greybox, 38d37a73a86448579fd7ba8c3ea1e42fc5bc0cb3 and is expected to be updated in forecast package soon.
