### ISSUE TITLE
Version 1.0.5 different from 1.0.4

### ISSUE THREAD

**Issue by notravarius** [config-i1/greybox#64]
Hey, I built a model using 1.0.4 version. Now, I installed 1.0.5 version and my code fails. When I want to get standar errors, now it has an additional warning regarding Choleski (I think that because of this now standar error are less accurate). I was very happy with predictions in 1.0.4, is there a way to install that version again? Thanks!!

**Comment by config-i1** [comment]
Hi notravarius,

Can you please provide a reproducible example for this? I will have a look and see if there is a bug in the new version.

In the meantime, you can install any previous version of greybox from source, downloading it from here: https://cran.r-project.org/src/contrib/Archive/greybox/

**Comment by config-i1** [comment]
No changes here for two months. I guess, this issue can be closed.
