### ISSUE TITLE
Plotting rollingOrigin object doesn't make sense when 'ci' and 'co' = FALSE

### ISSUE THREAD

**Issue by leungi** [config-i1/greybox#8]
This may be an enhancement.

When calling `ro()` with arguments  `ci` and `co` set to `TRUE`, and using native `plot()` on the `rollingOrigin` output, the indices for x-axis are not aligned correctly. This is illustrated in the vignette when plotting `plot(returnedValues1)`.

**Comment by config-i1** [comment]
Hi leungi,

Thanks for that! Can you, please, provide a bit more details? It seems to me that the thing is aligned okay.

**Comment by leungi** [comment]
Thanks for prompt response @config-i1.

I apologize, but the settings that has potential issue is when `ci` and `co` are both `FALSE`.

Please refer to sample run below.

``` r
library(smooth)
library(greybox)
library(tsbox)
x <- rnorm(100,100,10)
ourCall <- "predict(arima(x=data,order=c(0,1,1)),n.ahead=h)"
ourValue <- "pred"
returnedValues1 <- ro(x, h=3, origins=8, call=ourCall, value=ourValue, ci=FALSE, co=FALSE)
tail(returnedValues1$actuals, 10)
#> Time Series:
#> Start = 91 
#> End = 100 
#> Frequency = 1 
#>  [1] 102.02725  89.36349  93.15560  94.95822  89.88711  86.43818 115.72640
#>  [8]  81.53050  99.30922 112.15980
tail(x, 10)
#>  [1] 102.02725  89.36349  93.15560  94.95822  89.88711  86.43818 115.72640
#>  [8]  81.53050  99.30922 112.15980
returnedValues1$holdout
#>    origin93 origin94  origin95  origin96  origin97  origin98  origin99
#> h1 93.15560 94.95822  89.88711  86.43818 115.72640  81.53050  99.30922
#> h2 94.95822 89.88711  86.43818 115.72640  81.53050  99.30922 112.15980
#> h3 89.88711 86.43818 115.72640  81.53050  99.30922 112.15980        NA
#>    origin100
#> h1  112.1598
#> h2        NA
#> h3        NA
returnedValues1$pred
#>    origin93 origin94 origin95 origin96 origin97 origin98 origin99
#> h1 100.3281  100.271 100.1617 100.0188 100.1807 99.99038  99.9835
#> h2 100.3281  100.271 100.1617 100.0188 100.1807 99.99038  99.9835
#> h3 100.3281  100.271 100.1617 100.0188 100.1807 99.99038       NA
#>    origin100
#> h1  100.1053
#> h2        NA
#> h3        NA
plot(returnedValues1)
```
Referring to plot, the actual length of data `x` is only `100`, yet the plot shows blue dots (forecast) over index 100.

![](https://i.imgur.com/RSDGS8y.png)

Created on 2018-06-28 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by config-i1** [comment]
Done in 2c80e83e8c5da959dc6e5bc3ac7a9e5b76d363c8
This won't be available on CRAN for quite some time, so I'd recommend updating from github.

**Comment by leungi** [comment]
@config-i1, you're quick! Thank you very much.

A small suggestion (set the `type` in call to `plot()` in `plot.rollingOrigin()`) for consistency.:
```
 # Start plotting
    plot(y, ylab="Actuals", ylim=range(min(unlist(lapply(x,min,na.rm=T)),na.rm=T),
                                       max(unlist(lapply(x,max,na.rm=T)),na.rm=T)),
         type = 'l', # default to line type
         ...);
```

**Comment by config-i1** [comment]
Good idea, thanks! Done in 8f36803b1bbe0ee04c440f4d49e7445979fb6750
